name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Test
      run: go test ./test/services/ && go test ./test/repository/
        
    - name: Build
      run: go build ./cmd/main.go
    
    - name: Create a .env file
      uses: SpicyPizza/create-envfile@v1.3.0
      with:
        file_name: ".env"
    
    - name: Write File
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: ".env"
        contents: "ENV=production \n SERVER_PORT=80"
        write-mode: "overwride"
        
        
    - name: Heroku Deploy
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_app_name: "mighty-dawn-75375"
        heroku_email: "kevhernandez@outlook.com"
        heroku_api_key: "4f097be3-eb81-4b43-a017-cd0bd50cf33f"
        buildpack: ./main
        env_file: ".env"

    

    
